#FROM nginx:1.24-alpine
#
#MAINTAINER stanzhou "m@sq.mk"
#
#ARG ALPINE_REPO=https://mirrors.aliyun.com
#ARG URL_PREFIX=
#
#ENV NGINX_VERSION 1.21.6
#ENV MORE_HEADER_MODULE_VERSION 0.33
#ENV TIMEZONE Asia/Shanghai
#ENV LUAJIT_LIB=/usr/lib
#
## docker
#docker tag mumianzi/nginx:1.24-alpine mumianzi/nginx:1-alpine
